// <auto-generated />
using System;
using Assistant.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Assistant.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630145958_AddPriorityToCalendarEvent")]
    partial class AddPriorityToCalendarEvent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Assistant.Models.AutoAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_data");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("executed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<string>("TriggerData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trigger_data");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trigger_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("auto_actions", (string)null);
                });

            modelBuilder.Entity("Assistant.Models.CalendarEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean")
                        .HasColumnName("is_all_day");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("manual")
                        .HasColumnName("source");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId", "StartTime" }, "IX_calendar_events_user");

                    b.ToTable("calendar_events", (string)null);
                });

            modelBuilder.Entity("Assistant.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("role");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SessionId", "CreatedAt" }, "IX_chat_messages_session");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("Assistant.Models.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_activity");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId", "LastActivity" }, "IX_chat_sessions_user");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("Assistant.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("RelationshipLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("relationship_label");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("synced_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_contacts_user");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("Assistant.Models.EmailSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionItems")
                        .HasColumnType("text")
                        .HasColumnName("action_items");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeyPoints")
                        .HasColumnType("text")
                        .HasColumnName("key_points");

                    b.Property<string>("OriginalMessageId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_message_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("email_summaries", (string)null);
                });

            modelBuilder.Entity("Assistant.Models.ExtractedEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("ConfidenceScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0)
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_data");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("extracted_events", (string)null);
                });

            modelBuilder.Entity("Assistant.Models.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("CurrentValue")
                        .HasColumnType("double precision")
                        .HasColumnName("current_value");

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<double>("TargetValue")
                        .HasColumnType("double precision")
                        .HasColumnName("target_value");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("lần")
                        .HasColumnName("unit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId", "Status" }, "IX_goals_user_status");

                    b.ToTable("goals", (string)null);
                });

            modelBuilder.Entity("Assistant.Models.GoalProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("recorded_at");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("goal_progress", (string)null);
                });

            modelBuilder.Entity("Assistant.Models.KnowledgeBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Attribute")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("attribute");

                    b.Property<double>("Confidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0)
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("entity_name");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("ai_inferred")
                        .HasColumnName("source");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId", "EntityName" }, "IX_knowledge_entity");

                    b.HasIndex(new[] { "UserId", "EntityName", "Attribute" }, "UQ_knowledge_base_entry")
                        .IsUnique();

                    b.ToTable("knowledge_base", (string)null);
                });

            modelBuilder.Entity("Assistant.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ExtractedEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("extracted_event_id");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sender");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExtractedEventId");

                    b.HasIndex(new[] { "UserId", "ReceivedAt" }, "IX_messages_user");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Assistant.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("reminder")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex(new[] { "UserId", "ScheduledAt" }, "IX_notifications_sched");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Assistant.Models.ProductivityReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("CompletionRate")
                        .HasColumnType("double precision")
                        .HasColumnName("completion_rate");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("generated_at");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("period_type");

                    b.Property<string>("ReportData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("report_data");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("productivity_reports", (string)null);
                });

            modelBuilder.Entity("Assistant.Models.ScheduleConflict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("detected_at");

                    b.Property<Guid>("EventAId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_a_id");

                    b.Property<Guid>("EventBId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_b_id");

                    b.Property<string>("Resolution")
                        .HasColumnType("text")
                        .HasColumnName("resolution");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EventAId");

                    b.HasIndex("EventBId");

                    b.HasIndex(new[] { "UserId", "DetectedAt" }, "IX_conflicts_user");

                    b.ToTable("schedule_conflicts", (string)null);
                });

            modelBuilder.Entity("Assistant.Models.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("due_date");

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_minutes");

                    b.Property<string>("InputMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("text")
                        .HasColumnName("input_method");

                    b.Property<byte>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)2)
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId", "Status", "Priority" }, "IX_tasks_user_status");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("Assistant.Models.TaskCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#7F77DD")
                        .HasColumnName("color");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("task_categories", (string)null);
                });

            modelBuilder.Entity("Assistant.Models.TimeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Accepted")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.5)
                        .HasColumnName("score");

                    b.Property<DateTime>("SuggestedEnd")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("suggested_end");

                    b.Property<DateTime>("SuggestedStart")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("suggested_start");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "TaskId", "Score" }, "IX_time_slots_task");

                    b.ToTable("time_slots", (string)null);
                });

            modelBuilder.Entity("Assistant.Models.TimeTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_time");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TaskId");

                    b.HasIndex(new[] { "UserId", "StartTime" }, "IX_time_tracking_user");

                    b.ToTable("time_tracking", (string)null);
                });

            modelBuilder.Entity("Assistant.Models.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean")
                        .HasColumnName("completed");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("manual")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId", "DueDate" }, "IX_todos_user_due");

                    b.ToTable("todos", (string)null);
                });

            modelBuilder.Entity("Assistant.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("OtpCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Asia/Ho_Chi_Minh")
                        .HasColumnName("timezone");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "UQ_users_email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Assistant.Models.UserMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("key");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("manual")
                        .HasColumnName("source");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId", "Category", "Key" }, "IX_user_memories_lookup");

                    b.HasIndex(new[] { "UserId", "Category", "Key" }, "UQ_user_memories_key")
                        .IsUnique();

                    b.ToTable("user_memories", (string)null);
                });

            modelBuilder.Entity("Assistant.Models.VoiceTranscript", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiResponse")
                        .HasColumnType("text")
                        .HasColumnName("ai_response");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Transcript")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transcript");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "IX_voice_transcripts_user");

                    b.ToTable("voice_transcripts", (string)null);
                });

            modelBuilder.Entity("TaskCategoryMap", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("TaskId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("task_category_map", (string)null);
                });

            modelBuilder.Entity("Assistant.Models.AutoAction", b =>
                {
                    b.HasOne("Assistant.Models.User", "User")
                        .WithMany("AutoActions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_auto_actions_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Assistant.Models.CalendarEvent", b =>
                {
                    b.HasOne("Assistant.Models.User", "User")
                        .WithMany("CalendarEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_calendar_events_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Assistant.Models.ChatMessage", b =>
                {
                    b.HasOne("Assistant.Models.ChatSession", "Session")
                        .WithMany("ChatMessages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_chat_messages_session");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Assistant.Models.ChatSession", b =>
                {
                    b.HasOne("Assistant.Models.User", "User")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_chat_sessions_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Assistant.Models.Contact", b =>
                {
                    b.HasOne("Assistant.Models.User", "User")
                        .WithMany("Contacts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_contacts_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Assistant.Models.EmailSummary", b =>
                {
                    b.HasOne("Assistant.Models.User", "User")
                        .WithMany("EmailSummaries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_email_summaries_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Assistant.Models.ExtractedEvent", b =>
                {
                    b.HasOne("Assistant.Models.Message", "Message")
                        .WithMany("ExtractedEvents")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_extracted_events_message");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Assistant.Models.Goal", b =>
                {
                    b.HasOne("Assistant.Models.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_goals_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Assistant.Models.GoalProgress", b =>
                {
                    b.HasOne("Assistant.Models.Goal", "Goal")
                        .WithMany("GoalProgresses")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_gp_goal");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("Assistant.Models.KnowledgeBase", b =>
                {
                    b.HasOne("Assistant.Models.User", "User")
                        .WithMany("KnowledgeBases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_knowledge_base_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Assistant.Models.Message", b =>
                {
                    b.HasOne("Assistant.Models.ExtractedEvent", "ExtractedEvent")
                        .WithMany("Messages")
                        .HasForeignKey("ExtractedEventId")
                        .HasConstraintName("FK_messages_extracted_event");

                    b.HasOne("Assistant.Models.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_messages_user");

                    b.Navigation("ExtractedEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Assistant.Models.Notification", b =>
                {
                    b.HasOne("Assistant.Models.CalendarEvent", "Event")
                        .WithMany("Notifications")
                        .HasForeignKey("EventId")
                        .HasConstraintName("FK_notifications_event");

                    b.HasOne("Assistant.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_notifications_user");

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Assistant.Models.ProductivityReport", b =>
                {
                    b.HasOne("Assistant.Models.User", "User")
                        .WithMany("ProductivityReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_pr_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Assistant.Models.ScheduleConflict", b =>
                {
                    b.HasOne("Assistant.Models.CalendarEvent", "EventA")
                        .WithMany("ScheduleConflictEventAs")
                        .HasForeignKey("EventAId")
                        .IsRequired()
                        .HasConstraintName("FK_sc_event_a");

                    b.HasOne("Assistant.Models.CalendarEvent", "EventB")
                        .WithMany("ScheduleConflictEventBs")
                        .HasForeignKey("EventBId")
                        .IsRequired()
                        .HasConstraintName("FK_sc_event_b");

                    b.HasOne("Assistant.Models.User", "User")
                        .WithMany("ScheduleConflicts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_sc_user");

                    b.Navigation("EventA");

                    b.Navigation("EventB");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Assistant.Models.Task", b =>
                {
                    b.HasOne("Assistant.Models.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tasks_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Assistant.Models.TaskCategory", b =>
                {
                    b.HasOne("Assistant.Models.User", "User")
                        .WithMany("TaskCategories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_task_categories_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Assistant.Models.TimeSlot", b =>
                {
                    b.HasOne("Assistant.Models.Task", "Task")
                        .WithMany("TimeSlots")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_time_slots_task");

                    b.HasOne("Assistant.Models.User", "User")
                        .WithMany("TimeSlots")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_time_slots_user");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Assistant.Models.TimeTracking", b =>
                {
                    b.HasOne("Assistant.Models.TaskCategory", "Category")
                        .WithMany("TimeTrackings")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_tt_category");

                    b.HasOne("Assistant.Models.Task", "Task")
                        .WithMany("TimeTrackings")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("FK_tt_task");

                    b.HasOne("Assistant.Models.User", "User")
                        .WithMany("TimeTrackings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tt_user");

                    b.Navigation("Category");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Assistant.Models.Todo", b =>
                {
                    b.HasOne("Assistant.Models.User", "User")
                        .WithMany("Todos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_todos_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Assistant.Models.UserMemory", b =>
                {
                    b.HasOne("Assistant.Models.User", "User")
                        .WithMany("UserMemories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_user_memories_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Assistant.Models.VoiceTranscript", b =>
                {
                    b.HasOne("Assistant.Models.User", "User")
                        .WithMany("VoiceTranscripts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_voice_transcripts_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskCategoryMap", b =>
                {
                    b.HasOne("Assistant.Models.TaskCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_tcm_category");

                    b.HasOne("Assistant.Models.Task", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tcm_task");
                });

            modelBuilder.Entity("Assistant.Models.CalendarEvent", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("ScheduleConflictEventAs");

                    b.Navigation("ScheduleConflictEventBs");
                });

            modelBuilder.Entity("Assistant.Models.ChatSession", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("Assistant.Models.ExtractedEvent", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Assistant.Models.Goal", b =>
                {
                    b.Navigation("GoalProgresses");
                });

            modelBuilder.Entity("Assistant.Models.Message", b =>
                {
                    b.Navigation("ExtractedEvents");
                });

            modelBuilder.Entity("Assistant.Models.Task", b =>
                {
                    b.Navigation("TimeSlots");

                    b.Navigation("TimeTrackings");
                });

            modelBuilder.Entity("Assistant.Models.TaskCategory", b =>
                {
                    b.Navigation("TimeTrackings");
                });

            modelBuilder.Entity("Assistant.Models.User", b =>
                {
                    b.Navigation("AutoActions");

                    b.Navigation("CalendarEvents");

                    b.Navigation("ChatSessions");

                    b.Navigation("Contacts");

                    b.Navigation("EmailSummaries");

                    b.Navigation("Goals");

                    b.Navigation("KnowledgeBases");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("ProductivityReports");

                    b.Navigation("ScheduleConflicts");

                    b.Navigation("TaskCategories");

                    b.Navigation("Tasks");

                    b.Navigation("TimeSlots");

                    b.Navigation("TimeTrackings");

                    b.Navigation("Todos");

                    b.Navigation("UserMemories");

                    b.Navigation("VoiceTranscripts");
                });
#pragma warning restore 612, 618
        }
    }
}
